#------------ STACK ------------------------------
stack = list()
stack.append('ram')
stack.append('shyam')
stack.append('gita')
stack.append('sita')
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)

#----------- QUEUE -------------------------------
from collections import deque
queue = deque()
queue.append('ram')
queue.append('shyam')
queue.append('gita')
queue.append('sita')
print(queue)
print(queue.popleft())
print(queue)
print(queue.popleft())
print(queue)
print(queue.popleft())
print(queue)
print(queue.popleft())
print(queue)